name: Test
on: [push]
jobs:
  test:
    container:
      image: ruby:${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.1"]
        appraisal:
          - jekyll-35
          - jekyll-36
          - jekyll-37
          - jekyll-38
          - jekyll-39
          - jekyll-40
          - jekyll-41
          - jekyll-42
          - jekyll-43
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: bundle install
      - name: Install dependencies for each appraisal
        run: bundle exec appraisal install
      - name: Run tests
        run: bundle exec appraisal ${{ matrix.appraisal }} rake test
